import os
from anthropic import Anthropic
from dotenv import load_dotenv

# Load your secure environment variables (.env)
load_dotenv()

def translate_gherkin_to_playwright(gherkin_file_path: str) -> str:
    """
    Reads a local Gherkin .feature file and uses Claude to generate 
    a highly structured Playwright TypeScript automation spec.
    """
    # 1. Read the Gherkin feature file generated by your first agent
    if not os.path.exists(gherkin_file_path):
        return f"Error: The file {gherkin_file_path} was not found."
        
    with open(gherkin_file_path, "r") as file:
        gherkin_content = file.read()

    # 2. Initialize the Anthropic client
    client = Anthropic()

    # 3. Define the specialized SDET System Prompt
    system_prompt = """
You are an expert Senior SDET specialized in modern UI test automation using Playwright, TypeScript, and Node.js. 

Your task is to take a raw Gherkin feature script and translate every single scenario into a clean, working Playwright test block.

Adhere to these strict architectural guidelines:
1. Language: TypeScript. Use standard ESM import syntax: `import { test, expect } from '@playwright/test';`
2. Structure: Group the tests cleanly inside a `test.describe('Feature Name', () => { ... });` block matching the Gherkin feature description.
3. Best Practices: Use modern locator strategies prioritized by user-facing attributes (e.g., `page.getByRole()`, `page.getByLabel()`, `page.getByPlaceholder()`, or `page.getByTestId()`). Avoid hardcoded XPaths or CSS classes.
4. Clean Assertions: Use correct web-first assertions like `await expect(locator).toBeVisible();` or `await expect(locator).toHaveText();`.
5. Constraints: Output ONLY valid TypeScript code blocks. Do not wrap the code in markdown fences like ```typescript and do not include any introductory remarks, usage instructions, or explanation text. The file must be immediately runnable without cleanup.
"""

    print("🚀 Invoking Claude to convert Gherkin scenarios to Playwright automation scripts...")

    try:
        # 4. Make the API Call to Claude
        response = client.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=3000,
            temperature=0.1,  # Set ultra-low for razor-sharp code syntax adherence
            system=system_prompt,
            messages=[
                {
                    "role": "user",
                    "content": f"Translate this exact Gherkin feature into a Playwright TypeScript spec file:\n\n{gherkin_content}"
                }
            ]
        )
        
        return response.content[0].text

    except Exception as e:
        return f"An error occurred during Playwright code generation: {e}"


# --- Execution Block ---
if __name__ == "__main__":
    # Point to the feature file created by your first agent script
    input_feature_file = "coupon_validation.feature"
    output_spec_file = "coupon_validation.spec.ts"
    
    # Run the translation engine
    generated_playwright_code = translate_gherkin_to_playwright(input_feature_file)
    
    # Save the output directly as a TypeScript test spec file
    with open(output_spec_file, "w", encoding="utf-8") as spec_file:
        spec_file.write(generated_playwright_code)
        
    print(f"✨ Success! Playwright automation test suite saved cleanly to '{output_spec_file}'")        